# docker build -f docker/Dockerfile-neuralangelo -t chenhsuanlin/neuralangelo:23.04-py3 .
# docker push chenhsuanlin/neuralangelo:23.04-py3


FROM runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04
ARG DEBIAN_FRONTEND=noninteractive

# Set the working directory
WORKDIR /

# # Create workspace directory
# RUN mkdir /workspace

# Install basics
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    ffmpeg \
    g++ \
    git \
    libx264-dev \
    tmux \
    wget

# Set up Jupyter Notebook
RUN pip install notebook==6.5.5
RUN jupyter contrib nbextension install --user && \
    jupyter nbextension enable --py widgetsnbextension

# Update pip
RUN pip install --upgrade pip

# Code formatting
RUN pip install --upgrade \
    flake8 \
    pre-commit

# GIT Repo
WORKDIR /workspace
RUN git clone https://github.com/NVlabs/neuralangelo.git
WORKDIR /workspace/neuralangelo/
VOLUME [ "/workspace/neuralangelo" ]

# Install base Python libraries for Imaginaire
#COPY requirements.txt requirements.txt
ARG FORCE_CUDA=1
ARG TCNN_CUDA_ARCHITECTURES=70,72,75,80,86
RUN pip install --upgrade -r requirements.txt --ignore-installed

